### ISSUE TITLE
Characters page no longer shows characters

### ISSUE THREAD

**Issue by trapbuilder2** [emfmesquita/beyondhelp#36]
The characters page does not contain any characters or folders. Disabling the extension allows characters to show as normal.

**Comment by Hydrall** [comment]
I'm also seeing this issue - my characters have returned, but now the folders are gone, even the buttons.

**Comment by APenguini** [comment]
Same. Disabling extension works. (But stinks because beyond help is so very great!)

**Comment by emfmesquita** [comment]
Sorry for the delay. I just fixed it. A new version will come out as soon as Google approves it.

**Comment by APenguini** [comment]
Not clear if above fix rolled out but I still experience this same issue. And the Copy doesn't work any longer either.  I can turn the extension off and both work fine.  It's also doing some strange behavior with the folders, sometimes populating, sometimes I have to refresh to get folders to fill.
